"""Auto-detect machine class (GPU / Ollama reachability) and write
~/.config/odin_master/settings.toml. Idempotent.
"""
from __future__ import annotations

import os
import platform
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import requests


@dataclass
class MachineProfile:
    has_gpu: bool
    has_ollama: bool

    @property
    def enable_vector_search(self) -> bool:
        return self.has_gpu and self.has_ollama


def _has_gpu() -> bool:
    if shutil.which("nvidia-smi"):
        try:
            subprocess.check_output(["nvidia-smi"], stderr=subprocess.DEVNULL, timeout=5)
            return True
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
            pass
    if shutil.which("rocminfo"):
        return True
    return False


def _ollama_reachable(url: str = "http://127.0.0.1:11434") -> bool:
    try:
        return requests.get(f"{url}/api/version", timeout=2).status_code == 200
    except requests.RequestException:
        return False


def detect(probe_gpu=_has_gpu, probe_ollama=_ollama_reachable) -> MachineProfile:
    return MachineProfile(has_gpu=probe_gpu(), has_ollama=probe_ollama())


def settings_path() -> Path:
    if platform.system() == "Windows":
        base = Path(os.environ.get("APPDATA", Path.home() / "AppData/Roaming"))
    else:
        base = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return base / "odin_master" / "settings.toml"


_TEMPLATE = """# Generated by odin-master setup
enable_vector_search = {enable_vector_search}
ollama_url = "http://127.0.0.1:11434"
embedding_model = "qwen3-embedding:4b"
"""


def write_settings(profile: MachineProfile, path: Path | None = None) -> Path:
    out = path or settings_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    body = _TEMPLATE.format(
        enable_vector_search="true" if profile.enable_vector_search else "false"
    )
    out.write_text(body, encoding="utf-8")
    return out
