package main

// W2 drift guard -- the frozen woven fixture (w2-woven-run/main.odin) is regenerated by hand when
// the weaver changes; nothing else notices when it goes stale. This claim closes that loop: it
// holds the PRE-weave source verbatim, weaves it in-process with today's weaver, and asserts the
// sibling claim's checked-in file still begins with exactly that woven text (the file's tail is
// the human-written GENERATED comment, outside the weaver's output). Reds when either the weaver's
// output changes (regenerate w2-woven-run and re-freeze) or someone edits the fixture above the
// EOF import. count pins the injection census like w2-weave-count.

import "core:fmt"
import "core:os"
import "core:strings"
import "odin_lib:weave"

PREWEAVE :: `package main

import "core:fmt"

add :: proc(a, b: int) -> int {
	sum := a + b
	return sum
}

main :: proc() {
	xs := []int{1, 2, 3}
	acc := 0
	for x in xs {
		acc = add(acc, x)
	}
	if acc > 3 {
		big := acc * 2
		fmt.println(big)
	}
	fmt.println(acc)
}
`

main :: proc() {
	w := weave.weave_source(PREWEAVE, "claims/tele/w2-woven-run/main.odin")
	data, _ := os.read_entire_file("../w2-woven-run/main.odin", context.allocator)
	if len(data) == 0 {
		fmt.println("could not read ../w2-woven-run/main.odin")
		return
	}
	frozen := string(data)
	fmt.printf("count=%d\n", w.count)
	fmt.printf("frozen_starts_with_woven=%v\n", strings.has_prefix(frozen, w.src))
	if !strings.has_prefix(frozen, w.src) {
		// show where they part ways, for the regeneration diff
		n := min(len(frozen), len(w.src))
		i := 0
		for i < n && frozen[i] == w.src[i] {
			i += 1
		}
		lo := max(0, i - 40)
		fmt.printf("first byte diff at %d:\n  woven:  %s\n  frozen: %s\n",
			i, w.src[lo:min(i + 40, len(w.src))], frozen[lo:min(i + 40, len(frozen))])
	}
}
